package rentacar.ui.form.profile;

import javax.swing.JOptionPane;
import rentacar.domain.UserModel;
import rentacar.domain.request.RegisterRequestModel;
import rentacar.domain.response.LoginResponseModel;
import rentacar.domain.response.RegisterResponseModel;
import rentacar.repository.impl.UserRepositoryImpl;
import rentacar.ui.session.MySession;

/**
 *
 * @author mlade
 */
public class ChangePassword extends javax.swing.JDialog {
    
    UserRepositoryImpl userRepository = new UserRepositoryImpl();
    
    UserModel user = userRepository.getUser(Integer.parseInt(MySession.getInstance().getLoginUser().getUserId()));

    /**
     * Creates new form ProfileEditForm
     */
    public ChangePassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtCurrentPassword = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JTextField();
        txtNewRepeatedPassword = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblCurrentPasswordError = new javax.swing.JLabel();
        lblNewPasswordError = new javax.swing.JLabel();
        lblNewRepeatedPasswordError = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Password Change"));

        lblEmail.setText("Current password:");

        lblUsername.setText("New password:");

        lblName.setText("Repeat new password:");

        lblCurrentPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblCurrentPasswordError.setText(" ");

        lblNewPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblNewPasswordError.setText(" ");

        lblNewRepeatedPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblNewRepeatedPasswordError.setText(" ");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblUsername)
                            .addComponent(lblEmail))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNewRepeatedPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCurrentPasswordError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNewPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCurrentPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNewRepeatedPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtCurrentPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCurrentPasswordError)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPassword)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewPasswordError)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewRepeatedPassword)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewRepeatedPasswordError)
                .addGap(7, 7, 7)
                .addComponent(btnSave)
                .addGap(206, 206, 206))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean valid = true;
        boolean changed = false;

        LoginResponseModel loginResponse = null;

        lblCurrentPasswordError.setText("");
        lblNewPasswordError.setText("");
        lblNewRepeatedPasswordError.setText("");

        String currentPassword = txtCurrentPassword.getText();
        String newPassword = txtNewPassword.getText();
        String newRepeatedPassword = txtNewRepeatedPassword.getText();
        

        if (currentPassword.isEmpty()){
            lblCurrentPasswordError.setText("Current was not entered!");
            valid = false;
        }

        if (newPassword.isEmpty()){
            lblNewPasswordError.setText("New was not entered!");
            valid = false;
        }

        if (newRepeatedPassword.isEmpty()) {
            lblNewRepeatedPasswordError.setText("Repeated password was not entered!");
            valid = false;
        }
        
        if(!newPassword.equals(newRepeatedPassword)){
            String error = "New password error";
            lblNewRepeatedPasswordError.setText(error);
            lblNewPasswordError.setText(error);
            valid = false;
        }

        
        if (valid){

            loginResponse = userRepository.update(user, newPassword);
            

        }

        if (changed){
            dispose();
                
            JOptionPane.showMessageDialog(this, "Успешно регистровање!");

        }else {
            JOptionPane.showMessageDialog(this, loginResponse.getUserId());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrentPasswordError;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewPasswordError;
    private javax.swing.JLabel lblNewRepeatedPasswordError;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtCurrentPassword;
    private javax.swing.JTextField txtNewPassword;
    private javax.swing.JTextField txtNewRepeatedPassword;
    // End of variables declaration//GEN-END:variables
}
