package rentacar.ui.form;

import javax.swing.JFrame;
import rentacar.ui.form.car.CarSearchForm;
import rentacar.ui.form.login.LoginForm;

import rentacar.ui.form.register.RegisterForm;

/**
 *
 * @author mlade
 */
public class MainForm extends javax.swing.JFrame {

    public static void DISPOSE_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmCars = new javax.swing.JMenu();
        jmSearch = new javax.swing.JMenuItem();
        jmProfile = new javax.swing.JMenu();
        jmLogIn = new javax.swing.JMenuItem();
        jmRegister = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCars.setText("Cars");
        jmCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCarsActionPerformed(evt);
            }
        });

        jmSearch.setText("Search");
        jmSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSearchActionPerformed(evt);
            }
        });
        jmCars.add(jmSearch);

        jMenuBar1.add(jmCars);

        jmProfile.setText("Profile");

        jmLogIn.setText("Log in");
        jmLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmLogInActionPerformed(evt);
            }
        });
        jmProfile.add(jmLogIn);

        jmRegister.setText("Register");
        jmRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRegisterActionPerformed(evt);
            }
        });
        jmProfile.add(jmRegister);

        jMenuBar1.add(jmProfile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCarsActionPerformed
        
    }//GEN-LAST:event_jmCarsActionPerformed

    private void jmLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmLogInActionPerformed
        new LoginForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmLogInActionPerformed

    private void jmRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRegisterActionPerformed
        new RegisterForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmRegisterActionPerformed

    private void jmSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSearchActionPerformed
        new CarSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmSearchActionPerformed



   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCars;
    private javax.swing.JMenuItem jmLogIn;
    private javax.swing.JMenu jmProfile;
    private javax.swing.JMenuItem jmRegister;
    private javax.swing.JMenuItem jmSearch;
    // End of variables declaration//GEN-END:variables
}
